#!/bin/sh

case "$(printf "lock\\nsuspend\\nlogout\\nreboot\\npoweroff" | dmenu -p "⏻ ")" in
	lock) slock -lock ;;
	suspend) systemctl suspend ;;
	logout) pkill dwm ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
