#!/bin/sh

case "$(printf "lock\\nsuspend\\nlogout\\nreboot\\npoweroff" | dmenu -p "⏻ ")" in
	lock) slock ;;
	suspend) systemctl suspend && slock ;;
	logout) bspc quit ;;
	reboot) systemctl reboot ;;
	poweroff) systemctl poweroff ;;
esac
